name: Build with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Run PyInstaller
      run: |
        source .venv/bin/activate
        pyinstaller --clean --noconfirm your_spec_file.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: niv_louie
        path: dist/