name: Build with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m venv .venv
        .venv\Scripts\python.exe -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        .venv\Scripts\python.exe -m pip install -r requirements.txt --timeout=120

    - name: Install PyInstaller
      run: |
        .venv\Scripts\python.exe -m pip install pyinstaller

    - name: Run PyInstaller
      run: |
        .venv\Scripts\python.exe -m pyinstaller --clean --noconfirm niv_louie.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: niv_louie
        path: dist/