name: Build with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m venv .venv
        .venv/bin/pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        .venv/bin/pip install pyinstaller

    - name: Run PyInstaller
      run: |
        .env/bin/pyinstaller --clean --noconfirm niv_louie.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: niv_louie
        path: dist/